// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://releaseflow.net/api/rest' | (string & {});
};

/**
 * Authorization not provided error (401)
 *
 * The error information
 */
export type ErrorUnauthorized = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Insufficient access error (403)
 *
 * The error information
 */
export type ErrorForbidden = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Internal server error error (500)
 *
 * The error information
 */
export type ErrorInternalServerError = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Invalid input data error (400)
 *
 * The error information
 */
export type ErrorBadRequest = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Not found error (404)
 *
 * The error information
 */
export type ErrorNotFound = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

export type PolarIntegrationGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/integrations/polar';
};

export type PolarIntegrationGetAllErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationGetAllError = PolarIntegrationGetAllErrors[keyof PolarIntegrationGetAllErrors];

export type PolarIntegrationGetAllResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        description: string | null;
        accessToken: string;
        organizationId: string;
        environment: 'SANDBOX' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
        _count: {
            apps: number;
        };
    }>;
};

export type PolarIntegrationGetAllResponse = PolarIntegrationGetAllResponses[keyof PolarIntegrationGetAllResponses];

export type PolarIntegrationCreateData = {
    body: {
        name: string;
        description?: string;
        accessToken: string;
        organizationId: string;
        environment?: 'SANDBOX' | 'PRODUCTION';
    };
    path?: never;
    query?: never;
    url: '/integrations/polar';
};

export type PolarIntegrationCreateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationCreateError = PolarIntegrationCreateErrors[keyof PolarIntegrationCreateErrors];

export type PolarIntegrationCreateResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        accessToken: string;
        organizationId: string;
        environment: 'SANDBOX' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
    };
};

export type PolarIntegrationCreateResponse = PolarIntegrationCreateResponses[keyof PolarIntegrationCreateResponses];

export type PolarIntegrationDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/polar/{id}';
};

export type PolarIntegrationDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationDeleteError = PolarIntegrationDeleteErrors[keyof PolarIntegrationDeleteErrors];

export type PolarIntegrationDeleteResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type PolarIntegrationDeleteResponse = PolarIntegrationDeleteResponses[keyof PolarIntegrationDeleteResponses];

export type PolarIntegrationGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/polar/{id}';
};

export type PolarIntegrationGetByIdErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationGetByIdError = PolarIntegrationGetByIdErrors[keyof PolarIntegrationGetByIdErrors];

export type PolarIntegrationGetByIdResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        accessToken: string;
        organizationId: string;
        environment: 'SANDBOX' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
        apps: Array<{
            id: string;
            name: string;
            slug: string;
        }>;
    };
};

export type PolarIntegrationGetByIdResponse = PolarIntegrationGetByIdResponses[keyof PolarIntegrationGetByIdResponses];

export type PolarIntegrationUpdateData = {
    body: {
        name?: string;
        description?: string | null;
        accessToken?: string;
        organizationId?: string;
        environment?: 'SANDBOX' | 'PRODUCTION';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/polar/{id}';
};

export type PolarIntegrationUpdateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationUpdateError = PolarIntegrationUpdateErrors[keyof PolarIntegrationUpdateErrors];

export type PolarIntegrationUpdateResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        accessToken: string;
        organizationId: string;
        environment: 'SANDBOX' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
    };
};

export type PolarIntegrationUpdateResponse = PolarIntegrationUpdateResponses[keyof PolarIntegrationUpdateResponses];

export type PolarIntegrationDisconnectAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/integrations/polar';
};

export type PolarIntegrationDisconnectAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationDisconnectAppError = PolarIntegrationDisconnectAppErrors[keyof PolarIntegrationDisconnectAppErrors];

export type PolarIntegrationDisconnectAppResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        polarIntegrationId: string | null;
        lemonSqueezyIntegrationId: string | null;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
    };
};

export type PolarIntegrationDisconnectAppResponse = PolarIntegrationDisconnectAppResponses[keyof PolarIntegrationDisconnectAppResponses];

export type PolarIntegrationConnectAppData = {
    body: {
        integrationId: string;
    };
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/integrations/polar';
};

export type PolarIntegrationConnectAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationConnectAppError = PolarIntegrationConnectAppErrors[keyof PolarIntegrationConnectAppErrors];

export type PolarIntegrationConnectAppResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        polarIntegrationId: string | null;
        lemonSqueezyIntegrationId: string | null;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
    };
};

export type PolarIntegrationConnectAppResponse = PolarIntegrationConnectAppResponses[keyof PolarIntegrationConnectAppResponses];

export type PolarIntegrationGetProductsForAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/polar/products';
};

export type PolarIntegrationGetProductsForAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationGetProductsForAppError = PolarIntegrationGetProductsForAppErrors[keyof PolarIntegrationGetProductsForAppErrors];

export type PolarIntegrationGetProductsForAppResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        appId: string;
        productId: string;
        name: string | null;
        description: string | null;
        maxActivations: number | null;
        isPreorder: boolean;
        createdAt: string;
    }>;
};

export type PolarIntegrationGetProductsForAppResponse = PolarIntegrationGetProductsForAppResponses[keyof PolarIntegrationGetProductsForAppResponses];

export type PolarIntegrationGetBenefitsForAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/polar/benefits';
};

export type PolarIntegrationGetBenefitsForAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarIntegrationGetBenefitsForAppError = PolarIntegrationGetBenefitsForAppErrors[keyof PolarIntegrationGetBenefitsForAppErrors];

export type PolarIntegrationGetBenefitsForAppResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        appId: string;
        benefitId: string;
        name: string | null;
        createdAt: string;
    }>;
};

export type PolarIntegrationGetBenefitsForAppResponse = PolarIntegrationGetBenefitsForAppResponses[keyof PolarIntegrationGetBenefitsForAppResponses];

export type LemonSqueezyIntegrationGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/integrations/lemonsqueezy';
};

export type LemonSqueezyIntegrationGetAllErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationGetAllError = LemonSqueezyIntegrationGetAllErrors[keyof LemonSqueezyIntegrationGetAllErrors];

export type LemonSqueezyIntegrationGetAllResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        description: string | null;
        apiKey: string;
        storeId: string;
        environment: 'TEST' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
        _count: {
            apps: number;
        };
    }>;
};

export type LemonSqueezyIntegrationGetAllResponse = LemonSqueezyIntegrationGetAllResponses[keyof LemonSqueezyIntegrationGetAllResponses];

export type LemonSqueezyIntegrationCreateData = {
    body: {
        name: string;
        description?: string;
        apiKey: string;
        storeId: string;
        environment?: 'TEST' | 'PRODUCTION';
    };
    path?: never;
    query?: never;
    url: '/integrations/lemonsqueezy';
};

export type LemonSqueezyIntegrationCreateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationCreateError = LemonSqueezyIntegrationCreateErrors[keyof LemonSqueezyIntegrationCreateErrors];

export type LemonSqueezyIntegrationCreateResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        apiKey: string;
        storeId: string;
        environment: 'TEST' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
    };
};

export type LemonSqueezyIntegrationCreateResponse = LemonSqueezyIntegrationCreateResponses[keyof LemonSqueezyIntegrationCreateResponses];

export type LemonSqueezyIntegrationDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/lemonsqueezy/{id}';
};

export type LemonSqueezyIntegrationDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationDeleteError = LemonSqueezyIntegrationDeleteErrors[keyof LemonSqueezyIntegrationDeleteErrors];

export type LemonSqueezyIntegrationDeleteResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type LemonSqueezyIntegrationDeleteResponse = LemonSqueezyIntegrationDeleteResponses[keyof LemonSqueezyIntegrationDeleteResponses];

export type LemonSqueezyIntegrationGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/lemonsqueezy/{id}';
};

export type LemonSqueezyIntegrationGetByIdErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationGetByIdError = LemonSqueezyIntegrationGetByIdErrors[keyof LemonSqueezyIntegrationGetByIdErrors];

export type LemonSqueezyIntegrationGetByIdResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        apiKey: string;
        storeId: string;
        environment: 'TEST' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
        apps: Array<{
            id: string;
            name: string;
            slug: string;
        }>;
    };
};

export type LemonSqueezyIntegrationGetByIdResponse = LemonSqueezyIntegrationGetByIdResponses[keyof LemonSqueezyIntegrationGetByIdResponses];

export type LemonSqueezyIntegrationUpdateData = {
    body: {
        name?: string;
        description?: string | null;
        apiKey?: string;
        storeId?: string;
        environment?: 'TEST' | 'PRODUCTION';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/lemonsqueezy/{id}';
};

export type LemonSqueezyIntegrationUpdateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationUpdateError = LemonSqueezyIntegrationUpdateErrors[keyof LemonSqueezyIntegrationUpdateErrors];

export type LemonSqueezyIntegrationUpdateResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        apiKey: string;
        storeId: string;
        environment: 'TEST' | 'PRODUCTION';
        createdAt: string;
        updatedAt: string;
    };
};

export type LemonSqueezyIntegrationUpdateResponse = LemonSqueezyIntegrationUpdateResponses[keyof LemonSqueezyIntegrationUpdateResponses];

export type LemonSqueezyIntegrationDisconnectAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/integrations/lemonsqueezy';
};

export type LemonSqueezyIntegrationDisconnectAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationDisconnectAppError = LemonSqueezyIntegrationDisconnectAppErrors[keyof LemonSqueezyIntegrationDisconnectAppErrors];

export type LemonSqueezyIntegrationDisconnectAppResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        polarIntegrationId: string | null;
        lemonSqueezyIntegrationId: string | null;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
    };
};

export type LemonSqueezyIntegrationDisconnectAppResponse = LemonSqueezyIntegrationDisconnectAppResponses[keyof LemonSqueezyIntegrationDisconnectAppResponses];

export type LemonSqueezyIntegrationConnectAppData = {
    body: {
        integrationId: string;
    };
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/integrations/lemonsqueezy';
};

export type LemonSqueezyIntegrationConnectAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationConnectAppError = LemonSqueezyIntegrationConnectAppErrors[keyof LemonSqueezyIntegrationConnectAppErrors];

export type LemonSqueezyIntegrationConnectAppResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        polarIntegrationId: string | null;
        lemonSqueezyIntegrationId: string | null;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
    };
};

export type LemonSqueezyIntegrationConnectAppResponse = LemonSqueezyIntegrationConnectAppResponses[keyof LemonSqueezyIntegrationConnectAppResponses];

export type LemonSqueezyIntegrationGetProductsForAppData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/lemonsqueezy/products';
};

export type LemonSqueezyIntegrationGetProductsForAppErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type LemonSqueezyIntegrationGetProductsForAppError = LemonSqueezyIntegrationGetProductsForAppErrors[keyof LemonSqueezyIntegrationGetProductsForAppErrors];

export type LemonSqueezyIntegrationGetProductsForAppResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        appId: string;
        productId: string;
        name: string | null;
        description: string | null;
        maxActivations: number | null;
        isPreorder: boolean;
        createdAt: string;
    }>;
};

export type LemonSqueezyIntegrationGetProductsForAppResponse = LemonSqueezyIntegrationGetProductsForAppResponses[keyof LemonSqueezyIntegrationGetProductsForAppResponses];

export type ReleaseflowGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/apps';
};

export type ReleaseflowGetAllErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowGetAllError = ReleaseflowGetAllErrors[keyof ReleaseflowGetAllErrors];

export type ReleaseflowGetAllResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        slug: string;
        name: string;
        type: 'ELECTRON' | 'SPARKLE';
        githubRepo: string;
        changelogMode: 'NONE' | 'GLINK' | 'CUSTOM';
        sparkleVersionStrategy: 'SEMVER' | 'NUMERIC_BUILD';
        _count: {
            releases: number;
        };
        polarIntegration: {
            id: string;
            name: string;
        } | null;
        lemonSqueezyIntegration: {
            id: string;
            name: string;
        } | null;
    }>;
};

export type ReleaseflowGetAllResponse = ReleaseflowGetAllResponses[keyof ReleaseflowGetAllResponses];

export type ReleaseflowCreateData = {
    body: {
        name: string;
        slug: string;
        type: 'ELECTRON' | 'SPARKLE';
        githubRepo: string;
        sparklePublicKey?: string;
        minimumSystemVersion?: string;
        sparkleVersionStrategy?: 'SEMVER' | 'NUMERIC_BUILD';
        enableBeta?: boolean;
        enableAlpha?: boolean;
    };
    path?: never;
    query?: never;
    url: '/apps';
};

export type ReleaseflowCreateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowCreateError = ReleaseflowCreateErrors[keyof ReleaseflowCreateErrors];

export type ReleaseflowCreateResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        type: 'ELECTRON' | 'SPARKLE';
        githubRepo: string;
        changelogMode: 'NONE' | 'GLINK' | 'CUSTOM';
        sparklePublicKey: string | null;
        minimumSystemVersion: string | null;
        sparkleVersionStrategy: 'SEMVER' | 'NUMERIC_BUILD';
        enableBeta: boolean;
        enableAlpha: boolean;
        isPublic: boolean;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
        createdAt: string;
        updatedAt: string;
    };
};

export type ReleaseflowCreateResponse = ReleaseflowCreateResponses[keyof ReleaseflowCreateResponses];

export type ReleaseflowGetBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/apps/{slug}';
};

export type ReleaseflowGetBySlugErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowGetBySlugError = ReleaseflowGetBySlugErrors[keyof ReleaseflowGetBySlugErrors];

export type ReleaseflowGetBySlugResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        type: 'ELECTRON' | 'SPARKLE';
        githubRepo: string;
        changelogMode: 'NONE' | 'GLINK' | 'CUSTOM';
        sparklePublicKey: string | null;
        minimumSystemVersion: string | null;
        sparkleVersionStrategy: 'SEMVER' | 'NUMERIC_BUILD';
        enableBeta: boolean;
        enableAlpha: boolean;
        isPublic: boolean;
        glinkUsername: string | null;
        glinkProjectSlug: string | null;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
        polarIntegrationId: string | null;
        lemonSqueezyIntegrationId: string | null;
        user: {
            username: string | null;
        };
        polarIntegration: {
            id: string;
            name: string;
            environment: string;
        } | null;
        lemonSqueezyIntegration: {
            id: string;
            name: string;
            environment: string;
        } | null;
        releases: Array<{
            id: string;
            version: string;
            channel: 'STABLE' | 'BETA' | 'ALPHA';
            notes: string | null;
            changelogUrl: string | null;
            tagName: string;
            isPrerelease: boolean;
            isEnabled: boolean;
            publishedAt: string;
            assets: Array<{
                id: string;
                name: string;
                platform: 'DARWIN' | 'WINDOWS' | 'LINUX';
                arch: string | null;
                size: number;
                downloadUrl: string;
            }>;
        }>;
    };
};

export type ReleaseflowGetBySlugResponse = ReleaseflowGetBySlugResponses[keyof ReleaseflowGetBySlugResponses];

export type ReleaseflowDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/apps/{id}';
};

export type ReleaseflowDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowDeleteError = ReleaseflowDeleteErrors[keyof ReleaseflowDeleteErrors];

export type ReleaseflowDeleteResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type ReleaseflowDeleteResponse = ReleaseflowDeleteResponses[keyof ReleaseflowDeleteResponses];

export type ReleaseflowUpdateData = {
    body: {
        name?: string;
        sparklePublicKey?: string | null;
        minimumSystemVersion?: string | null;
        sparkleVersionStrategy?: 'SEMVER' | 'NUMERIC_BUILD';
        enableBeta?: boolean;
        enableAlpha?: boolean;
        isPublic?: boolean;
        polarIntegrationId?: string | null;
        lemonSqueezyIntegrationId?: string | null;
        changelogMode?: 'NONE' | 'GLINK' | 'CUSTOM';
        glinkUsername?: string | null;
        glinkProjectSlug?: string | null;
        polarProductIds?: Array<string>;
        polarBenefitIds?: Array<string>;
        lemonSqueezyProductIds?: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/apps/{id}';
};

export type ReleaseflowUpdateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowUpdateError = ReleaseflowUpdateErrors[keyof ReleaseflowUpdateErrors];

export type ReleaseflowUpdateResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        slug: string;
        name: string;
        type: 'ELECTRON' | 'SPARKLE';
        githubRepo: string;
        changelogMode: 'NONE' | 'GLINK' | 'CUSTOM';
        sparklePublicKey: string | null;
        minimumSystemVersion: string | null;
        sparkleVersionStrategy: 'SEMVER' | 'NUMERIC_BUILD';
        enableBeta: boolean;
        enableAlpha: boolean;
        isPublic: boolean;
        licenseProvider: 'NONE' | 'POLAR' | 'LEMONSQUEEZY' | 'INTERNAL';
        createdAt: string;
        updatedAt: string;
    };
};

export type ReleaseflowUpdateResponse = ReleaseflowUpdateResponses[keyof ReleaseflowUpdateResponses];

export type ReleaseflowSyncReleasesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/apps/{id}/sync';
};

export type ReleaseflowSyncReleasesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowSyncReleasesError = ReleaseflowSyncReleasesErrors[keyof ReleaseflowSyncReleasesErrors];

export type ReleaseflowSyncReleasesResponses = {
    /**
     * Successful response
     */
    200: {
        created: number;
        updated: number;
        newReleaseIds: Array<string>;
        newReleaseVersions: Array<string>;
    };
};

export type ReleaseflowSyncReleasesResponse = ReleaseflowSyncReleasesResponses[keyof ReleaseflowSyncReleasesResponses];

export type ReleaseflowGetUrlsData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/apps/{slug}/urls';
};

export type ReleaseflowGetUrlsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowGetUrlsError = ReleaseflowGetUrlsErrors[keyof ReleaseflowGetUrlsErrors];

export type ReleaseflowGetUrlsResponses = {
    /**
     * Successful response
     */
    200: {
        download: {
            auto: string;
            darwin: string;
            darwinArm64: string;
            windows?: string;
            linux?: string;
        };
        page: {
            stable: string;
            beta?: string;
            alpha?: string;
        };
        releases: string;
        releasesByChannel: {
            stable: string;
            beta?: string;
            alpha?: string;
        };
        sparkle?: {
            appcast: string;
            appcastBeta?: string;
            appcastAlpha?: string;
        };
        electron?: {
            darwin: string;
            darwinBeta?: string;
            darwinAlpha?: string;
            windows: string;
            windowsBeta?: string;
            windowsAlpha?: string;
            linux: string;
            linuxBeta?: string;
            linuxAlpha?: string;
        };
    };
};

export type ReleaseflowGetUrlsResponse = ReleaseflowGetUrlsResponses[keyof ReleaseflowGetUrlsResponses];

export type ReleaseflowDeleteReleaseData = {
    body?: never;
    path: {
        releaseId: string;
    };
    query?: never;
    url: '/releases/{releaseId}';
};

export type ReleaseflowDeleteReleaseErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowDeleteReleaseError = ReleaseflowDeleteReleaseErrors[keyof ReleaseflowDeleteReleaseErrors];

export type ReleaseflowDeleteReleaseResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        version: string;
    };
};

export type ReleaseflowDeleteReleaseResponse = ReleaseflowDeleteReleaseResponses[keyof ReleaseflowDeleteReleaseResponses];

export type ReleaseflowUpdateReleaseData = {
    body: {
        notes?: string | null;
        changelogUrl?: string | null;
        isEnabled?: boolean;
    };
    path: {
        releaseId: string;
    };
    query?: never;
    url: '/releases/{releaseId}';
};

export type ReleaseflowUpdateReleaseErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowUpdateReleaseError = ReleaseflowUpdateReleaseErrors[keyof ReleaseflowUpdateReleaseErrors];

export type ReleaseflowUpdateReleaseResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        version: string;
        channel: 'STABLE' | 'BETA' | 'ALPHA';
        notes: string | null;
        changelogUrl: string | null;
        tagName: string;
        isPrerelease: boolean;
        isEnabled: boolean;
        publishedAt: string;
        assets: Array<{
            id: string;
            name: string;
            platform: 'DARWIN' | 'WINDOWS' | 'LINUX';
            arch: string | null;
            size: number;
            downloadUrl: string;
        }>;
    };
};

export type ReleaseflowUpdateReleaseResponse = ReleaseflowUpdateReleaseResponses[keyof ReleaseflowUpdateReleaseResponses];

export type ReleaseflowToggleReleaseData = {
    body?: never;
    path: {
        releaseId: string;
    };
    query?: never;
    url: '/releases/{releaseId}/toggle';
};

export type ReleaseflowToggleReleaseErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ReleaseflowToggleReleaseError = ReleaseflowToggleReleaseErrors[keyof ReleaseflowToggleReleaseErrors];

export type ReleaseflowToggleReleaseResponses = {
    /**
     * Successful response
     */
    200: {
        isEnabled: boolean;
    };
};

export type ReleaseflowToggleReleaseResponse = ReleaseflowToggleReleaseResponses[keyof ReleaseflowToggleReleaseResponses];
